# -*- coding: utf-8 -*-
"""computer_components_classifier_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LMTkC7m3fUzFCsVFvwVFi5dqvLTuz62J
"""

import streamlit as st
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
from PIL import Image

st.title("Computer Component Classifier App")

model = load_model('component_classifier.h5')

def predict(img):
    img = img.resize((128, 128))
    img_array = image.img_to_array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    prediction = model.predict(img_array)
    return prediction

uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    img = Image.open(uploaded_file)
    st.image(img, caption='Uploaded Image.', use_column_width=True)
    st.write("")
    st.write("Classifying...")
    prediction = predict(img)
    class_names = list(train_data.class_indices.keys())
    st.write(f"Prediction: {class_names[np.argmax(prediction)]}")

